config/routes.rb
Rails.application.routes.draw do
  resources :authors,:reviews,:biocards
  post 'authors/new',to: 'authors#create'
  post 'reviews/new',to: 'reviews#create'
  post 'biocards/new',to: 'biocards#create'
  root 'authors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :reviews
  has_many :biocards
  has_attached_file :image,
                    styles: {
                      thumb: ["300x300#", :jpeg],
                      original: [:jpeg]
                    }

  validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 1.megabyte },
                     url: "/system/:hash.:extension",
                     hash_secret: "f808339f3042174df519539e79c39bd9ea13fd09ff7a38e8f0e05ceb39fb5fa61c16b897c128b9f18afbc1dafc62162311410e2d4209ea9b8e3fd65d4e94190e"
end

app/models/biocard.rb
class Biocard < ApplicationRecord
  belongs_to :author
  has_attached_file :image,
                    styles: {
                      thumb: ["130x130#", :jpeg],
                      original: [:jpeg]
                    }
  validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 1.megabyte }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def create
    @author = Author.new(author_params)
    @author.save
    if @author.errors.any?
      render :'authors/new'
    else
      redirect_to @author
    end
  end

  def show
    @author = Author.find_by(id: params[:id])
    @cards = @author.biocards.order("year")
    @author_reviews = Review.where(author_id: [@author.id]).to_a
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find_by(id: params[:id])
  end

  def update
    @author = Author.update(params[:id],author_params)
    @author.save
    if @author.errors.any?
      render 'edit'
    else
      redirect_to author_path
    end
  end

  def delete
    @author = Author.find(params[:id])
  end
  def destroy
    Author.find(params[:id]).destroy
    redirect_to authors_path
  end
  private
    def author_params
      params.require(:author).permit(:name,:bio,:image,:dob)
    end
end

app/controllers/biocards_controller.rb
class BiocardsController < ApplicationController

  def index
    @biocards = Biocard.all
  end

  def show
    @biocard = Biocard.find(params[:id])
  end

  def new
    @biocard = Biocard.new
  end

  def create
    @biocard = Biocard.create(biocard_params)
    if @biocard.save
      redirect_to @biocard
    else
      redirect_to :back
    end
  end

  def edit
    @biocard = Biocard.find_by(id: params[:id])
  end

  def update
    @biocard = Biocard.update(params[:id],biocard_params)
    @biocard.save
    if @biocard.errors.any?
      render 'edit'
    else
      redirect_to biocard_path
    end
  end

  def destroy
    Biocard.find(params[:id]).destroy
    redirect_to biocards_path
  end

  private
    def biocard_params
      params.require(:biocard).permit(:description,:name,:year,:author_id,:image)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
      @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.save
    if @review.errors.any?
      render :'reviews/new'
    else
      redirect_to @review
    end
  end

  def update
    @review = Review.update(params[:id],review_params)
    @review.save
    if @review.errors.any?
      render 'edit'
    else
      redirect_to review_path
    end
  end

  def edit
    @review = Review.find_by(id: params[:id])
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to reviews_path
  end

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find_by(id: params[:id])
  end

  private
    def review_params
      params.require(:review).permit(:title,:body,:author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/biocards_helper.rb
module BiocardsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/authors/edit.html.erb
<h1>Редактировать</h1>
<%= form_for (@author) do |form| %>
  <p>Имя<%= form.text_field :name %></p>
  <p>Биография<%= form.text_area :bio %></p>
  <p>Дата рождения<%= form.date_field :dob %></p>
  <p><%= form.label :image %></p>
  <p><%= form.file_field :image %></p>
  <%= form.submit "Сохранить" %>
<% end %>

app/views/authors/index.html.erb
<style type="text/css">
  a:link { color: #000000; text-decoration: none}
  a:visited { color: #000000; text-decoration: none}
  a:hover { color: #3366CC; text-decoration: underline}
  a:active { color: #000000; text-decoration: none}
</style>
<div class="zglvk">Все писатели</div>
<% @authors.each do |author| %>
  <div class="img_cntrd">
    <div>
      <p><%= image_tag(author.image.url(:thumb)) if author.image.exists? %></p>
      <p class="name_links"><%= link_to author.name,author_path(author)%></p>
      <p class="name_links"><%= author.dob%></p>
    </div>
  </div>
<% end %>

app/views/authors/new.html.erb
<h1>Добавить писателя</h1>
<%= form_for :author, url: new_author_path do |form| %>
  <p>Имя<%= form.text_field :name %></p>
  <p>Биография<%= form.text_area :bio %></p>
  <p>Дата рождения<%= form.date_field :dob %></p>
  <p><%= form.label :image %></p>
  <p><%= form.file_field :image %></p>
  <%= form.submit "Сохранить" %>
<% end %>

app/views/authors/show.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="authors.scss">
    <style type="text/css">
      a:link, a:visited {
        background-color: #5aafd6;
        color: white;
        padding: 14px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
      }

      a:hover, a:active {
        background-color: #6e98db;
      }
    </style>
</head>
<div class="back_button">
  <%= link_to "⇠ На главную",:authors%>
</div>
<body>
    <div class="a_name"><%= @author.name %></div>
    <div class="img_cntrd">
      <%= image_tag(@author.image.url(:thumb)) if @author.image.exists? %>
    </div>
    <div class="bio">
      <p><%= @author.bio %></p>
    </div>
    <hr style="border-color:#5aafd6;">
    <div id="carousel" class="carousel">
      <button class="arrow prev">⤌</button>
    <div class="gallery">
      <ul class="images">
        <% @cards.each do |c| %>
          <li><img title= "<%=c.description%>" src=<%=c.image.url(:thumb)%>></li>
        <% end %>
      </ul>
    </div>
    <button class="arrow next">⤍</button>
  </div>
  <script>
    $(document).ready(function(){
      let i = 1;
      for(let li of carousel.querySelectorAll('li')) {
        li.style.position = 'relative';
        li.insertAdjacentHTML('beforeend', `<span style="position:absolute;left:0;top:0">${i}</span>`);
        i++;
      }
      let width = 130;
      let count = 1;
      let list = carousel.querySelector('ul');
      let listElems = carousel.querySelectorAll('li');
      let position = 0;
      carousel.querySelector('.prev').onclick = function() {
        position += width * count;
        position = Math.min(position, 0)
        list.style.marginLeft = position + 'px';
      };
      carousel.querySelector('.next').onclick = function() {
        position -= width * count;
        position = Math.max(position, -width * (listElems.length - count));
        list.style.marginLeft = position + 'px';
      };
    });
    </script>
    <div class="rev_button">
      <%= link_to "Изменить", edit_author_url(@author.id) %>
      <%= link_to "Удалить", author_path(@author.id), method: :delete, data: {confirm: 'Вы уверены,что хотите удалить писателя?'} %>
      <%= link_to "Случайная рецензия", review_path(@author_reviews.sample.id) %>
    </div>
  </body>
</html>

app/views/biocards/edit.html.erb
<h1>Редактировать</h1>
<%= form_for (@biocard) do |form| %>
  <p>Событием<%= form.text_field :name %></p>
  <p>Содержание<%= form.text_area :description %></p>
  <p>Год<%= form.text_field :year %></p>
  <p>О ком <%= form.collection_select :author_id, Author.order(:name),:id,:name %></p>
  <p><%= form.label :image %></p>
  <p><%= form.file_field :image %></p>
  <%= form.submit "Сохранить" %>
<% end %>

app/views/biocards/index.html.erb
<h1>Все карточки писателей</h1>
<% @biocards.each do |b| %>
  <div>
    <div>
      <p><%= link_to b.name,biocard_path(b)%></p>
    </div>
  </div>
<% end %>
<p> <%= link_to "Новая карточка писателя", new_biocard_path %> </p>

app/views/biocards/new.html.erb
<h1>Создать</h1>
<%= form_for :biocard, url: new_biocard_path do |form| %>
  <p>Событие<%= form.text_field :name %></p>
  <p>Содержание<%= form.text_field :description %></p>
  <p>Год<%= form.text_field :year %></p>
  <p>Писатель <%= form.collection_select :author_id, Author.order(:name),:id,:name %></p>
  <p><%= form.label :image %></p>
  <p><%= form.file_field :image %></p>
  <%= form.submit "Сохранить" %>
<% end %>

app/views/biocards/show.html.erb
<h1> <%=@biocard.name%> </h1>
<div class="img_cntrd">
  <%= image_tag(@biocard.image.url(:thumb)) if @biocard.image.exists? %>
</div>
<div>
  <p> Содержание: <%= @biocard.description %></p>
  <p> Год: <%= @biocard.year %></p>
  <p> О ком: <%= @biocard.author.name %></p>
</div>
<%= link_to "Изменить", edit_biocard_url(@biocard.id) %>
<%= link_to "Удалить", biocard_path(@biocard.id), method: :delete, data: {confirm: 'Вы уверены,что хотите удалить карточку писателя?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Literature</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Редактировать</h1>
<%= form_for (@review) do |form| %>
  <p>Название<%= form.text_field :title %></p>
  <p>Содержание<%= form.text_area :body %></p>
  <p>О ком <%= form.collection_select :author_id, Author.order(:name),:id,:name %></p>
  <%= form.submit "Сохранить" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Все рецензии</h1>
<% @reviews.each do |review| %>
  <div>
    <div>
      <p><%= link_to review.title,review_path(review)%></p>
    </div>
  </div>
<% end %>
<p> <%= link_to "Новая рецензия", new_review_path %> </p>

app/views/reviews/new.html.erb
<h1>Создать</h1>
<%= form_for :review, url: new_review_path do |form| %>
  <p>Название<%= form.text_field :title %></p>
  <p>Содержание<%= form.text_field :body %></p>
  <p>О ком <%= form.collection_select :author_id, Author.order(:name),:id,:name %></p>
  <%= form.submit "Сохранить" %>
<% end %>

app/views/reviews/show.html.erb
<style type="text/css">
  a:link, a:visited {
    background-color: #5aafd6;
    color: white;
    padding: 14px 25px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
  }

  a:hover, a:active {
    background-color: #6e98db;
  }
</style>
<div class="back_button">
<%= link_to "⇠ Назад",:back%>
</div>
<div class='header'><%= @review.title %></div>
<div class="rev_body">
  <p><%= @review.body %></p>
</div>
<%= link_to "Изменить", edit_review_url(@review.id) %>
<%= link_to "Удалить", review_path(@review.id), method: :delete, data: {confirm: 'Вы уверены,что хотите удалить рецензию?'} %>